fix multiple entityIDs

diff --git a/saml2-metadata-verifier b/saml2-metadata-verifier
--- a/saml2-metadata-verifier
+++ b/saml2-metadata-verifier
@@ -18,12 +18,16 @@ verify() {
     for file in "$tmp_dir"/*; do
         entityID=$(cat "$file" | grep "entityID" | cut -d= -f2 | tr -d '"')
         echo "verifying metadata for entityID: $entityID"
-        XML_CATALOG_FILES="xcatalog/saml-metadata.xml" xmllint --pretty 1 --schema saml-2.0-os/saml-schema-metadata-2.0.xsd "$2" "$file"
-    done
-         
-    rm -rf "$tmp_dir"
-}
 
+        # return exit code
+        cat "$file" | XML_CATALOG_FILES="xcatalog/saml-metadata.xml" xmllint --schema saml-2.0-os/saml-schema-metadata-2.0.xsd "$2" -
+        err=$?
+        echo
+    done
+
+    rm -rf "$tmp_dir"
+    exit $err 
+}
 
 usage() {
   printf "%s\n" "Usage: ${0##*/} [OPTIONS...]"
@@ -39,7 +43,6 @@ main() {
         case "${1}" in
             -f|--file)
             verify "$2" $OPTIONS
-            exit 0
             ;;
             -v|--verbose)
             OPTIONS="--load-trace"
